# Generated by Django 4.0.3 on 2022-04-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.FileField(upload_to='pics'),
        ),
    ]
